-- FOREIGN KEYS SCRIPT

ALTER TABLE POLICY ADD FOREIGN KEY (RT_ID) REFERENCES RISK(RT_ID)

ALTER TABLE CITY ADD FOREIGN KEY (ST_ID) REFERENCES STATE_OF_ORIGIN(ST_ID)

ALTER TABLE EMPLOYEE ADD FOREIGN KEY (CP_ID) REFERENCES INSURANCE_COMPANY(CP_ID)

ALTER TABLE EMPLOYEE ADD FOREIGN KEY (ROLE_ID) REFERENCES EMPLOYEE_ROLE(ROLE_ID)

ALTER TABLE CLIENT ADD FOREIGN KEY (CT_ID) REFERENCES TYPE_OF_CLIENT(CT_ID)
ALTER TABLE CLIENT ADD FOREIGN KEY (POLICY_ID ) REFERENCES POLICY(POLICY_ID)

ALTER TABLE BANK_ACCOUNT ADD FOREIGN KEY (BANK_ID ) REFERENCES BANK(BANK_ID)
ALTER TABLE BANK_ACCOUNT ADD FOREIGN KEY (CLIENT_ID ) REFERENCES CLIENT(CLIENT_ID)
ALTER TABLE BANK_ACCOUNT ADD FOREIGN KEY (CP_ID ) REFERENCES INSURANCE_COMPANY(CP_ID)

ALTER TABLE PRICELIST ADD FOREIGN KEY (CP_ID ) REFERENCES INSURANCE_COMPANY(CP_ID)

ALTER TABLE INSURANCE_COMPANY ADD FOREIGN KEY (CITY_ID ) REFERENCES CITY(CITY_ID)

ALTER TABLE POLICY ADD FOREIGN KEY (CLIENT_ID  ) REFERENCES CLIENT(CLIENT_ID )
ALTER TABLE POLICY ADD FOREIGN KEY (RT_ID  ) REFERENCES RISK(RT_ID )
ALTER TABLE POLICY ADD FOREIGN KEY (II_ID  ) REFERENCES SUBJECT_OF_INSURANCE(II_ID )
ALTER TABLE POLICY ADD FOREIGN KEY (CP_ID ) REFERENCES INSURANCE_COMPANY(CP_ID )
ALTER TABLE POLICY ADD FOREIGN KEY (CURRENCY_ID  ) REFERENCES CURRENCY(CURRENCY_ID )
ALTER TABLE POLICY ADD FOREIGN KEY (EN_ID ) REFERENCES EMPLOYEE(EN_ID )
ALTER TABLE POLICY ADD FOREIGN KEY (PDV_ID ) REFERENCES PDV(PDV_ID )

ALTER TABLE RATE_OF_PDV ADD FOREIGN KEY (PDV_ID ) REFERENCES PDV(PDV_ID )

ALTER TABLE PRICELIST_ITEM ADD FOREIGN KEY (PRICELIST_ID ) REFERENCES PRICELIST(PRICELIST_ID)

ALTER TABLE BUSINESS_YEAR ADD FOREIGN KEY (CP_ID ) REFERENCES INSURANCE_COMPANY(CP_ID)

ALTER TABLE HOME ADD FOREIGN KEY (HT_ID ) REFERENCES TYPE_OF_HOME(HT_ID)

ALTER TABLE TYPE_OF_INSURANCE ADD FOREIGN KEY (PACKAGE_ID ) REFERENCES PACKAGE(PACKAGE_ID)

ALTER TABLE CAR ADD FOREIGN KEY (CLIENT_ID ) REFERENCES CLIENT(CLIENT_ID)

